unstable_features = true
brace_style = "AlwaysNextLine"
comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Item"
wrap_comments = true
indent_style = "Visual"
fn_single_line = true
control_brace_style = "AlwaysNextLine"